version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - '${BACKEND_PORT}:3000'
      - '${STUDIO_PORT}:5555'
    depends_on:
      - db
    volumes:
      - './backend:/var/www'
    tty: true
    stdin_open: true
  db:
    image: 'mysql:8.0.32'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    hostname: 'anidge'
    user: 'root'
    volumes:
      - 'db:/var/lib/mysql'
volumes:
  db:
    driver: local